
version: '3.9'

services:
  db:
    image: mysql:8
    container_name: mysql_gesapp
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: suivi_apprenants
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_gesapp
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8082:80" 
    depends_on:
      - db
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

