services:
 db:
   image: mysql:8
   environment:
     MYSQL_ROOT_PASSWORD: rootpassword
     MYSQL_DATABASE: suivi_apprenants
     MYSQL_USER: user
     MYSQL_PASSWORD: password
   ports:
     - "3307:3306"
   volumes:
     - db_data:/var/lib/mysql


 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   environment:
     PMA_HOST: db
     PMA_USER: root
     PMA_PASSWORD: rootpassword
   ports:
     - "8080:80"
   depends_on:
     - db


volumes:
 db_data:


